spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/port
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml